kind: CronJob
apiVersion: batch/v1

metadata:
    name: scripts-noches

spec:
    schedule: "*/5 * * * *"
    jobTemplate:
        spec:
            template:
                spec: 
                    containers:
                        -   name:     script
                            image:    miscript:latest
                            imagePullPolicy: IfNotPresent
                    volumeMounts:
                        - name: datos
                          mountPath: /tmp/datos
                    restartPolicy: Never
    volumes:
        - name: datos
          persistentVolumeClaim:
            claimName: peticion-volumen-scripts
            