kind: PersistentVolumeClaim
apiVersion: v1

metadata:
    name: peticion-volumen-scripts

spec:
    resources:
      requests:
        storage: 1Gi
    storageClassName: gp3
    accessModes:
      - ReadWriteOnce